import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { IRiskAnalysis } from '@/models/RiskAnalysis';

interface PDFRiskData {
    questionId: number;
    level: string;
    question: string;
    answer: string;
    likelihood: number;
    impact: number;
    riskScore: number;
    riskLevel: string;
    gap: string;
    threat: string;
    mitigation: string;
    impactLabel: string;
    likelihoodLabel: string;
}

export const generatePDFReport = async (analysis: IRiskAnalysis): Promise<Buffer> => {
    const doc = new jsPDF();

    // Prepare data
    const allRisks: PDFRiskData[] = [
        ...analysis.operational,
        ...analysis.tactical,
        ...analysis.strategic
    ].map(item => ({
        questionId: item.questionId,
        level: item.level,
        question: item.question,
        answer: item.answer,
        likelihood: item.analysis.likelihood,
        impact: item.analysis.impact,
        riskScore: item.analysis.riskScore,
        riskLevel: item.analysis.riskLevel,
        gap: item.analysis.gap,
        threat: item.analysis.threat,
        mitigation: item.analysis.mitigation,
        impactLabel: item.analysis.impactLabel || 'Moderate',
        likelihoodLabel: item.analysis.likelihoodLabel || 'Moderate'
    }));

    // Generate report sections
    generateCoverPage(doc, analysis);
    generateExecutiveSummary(doc, analysis, allRisks);
    generateRiskMatrix(doc, allRisks);
    generateDetailedFindings(doc, allRisks);
    generateRecommendations(doc, allRisks);

    return Buffer.from(doc.output('arraybuffer'));
};

const generateCoverPage = (doc: jsPDF, analysis: IRiskAnalysis) => {
    // Header
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Cybersecurity Risk Assessment Report', 105, 40, { align: 'center' });

    // Company info
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`Company: ${analysis.company}`, 105, 60, { align: 'center' });
    doc.text(`Category: ${analysis.category}`, 105, 75, { align: 'center' });
    doc.text(`Assessment Date: ${new Date(analysis.createdAt).toLocaleDateString()}`, 105, 90, { align: 'center' });

    // Logo placeholder
    doc.setDrawColor(200, 200, 200);
    doc.rect(80, 110, 50, 30);
    doc.setFontSize(10);
    doc.text('Company Logo', 105, 127, { align: 'center' });

    // Footer
    doc.setFontSize(12);
    doc.text('Generated by INSA Risk Analysis System', 105, 250, { align: 'center' });
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 105, 265, { align: 'center' });

    doc.addPage();
};

const generateExecutiveSummary = (doc: jsPDF, analysis: IRiskAnalysis, risks: PDFRiskData[]) => {
    let yPos = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', 20, yPos);
    yPos += 15;

    // Assessment overview
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`This cybersecurity risk assessment evaluated ${analysis.metadata.totalQuestions} security controls`, 20, yPos);
    yPos += 8;
    doc.text(`across strategic (${analysis.metadata.levels.strategic}), tactical (${analysis.metadata.levels.tactical}), and operational (${analysis.metadata.levels.operational}) levels.`, 20, yPos);
    yPos += 15;

    // Risk distribution
    const riskCounts = {
        CRITICAL: risks.filter(r => r.riskLevel === 'CRITICAL').length,
        HIGH: risks.filter(r => r.riskLevel === 'HIGH').length,
        MEDIUM: risks.filter(r => r.riskLevel === 'MEDIUM').length,
        LOW: risks.filter(r => r.riskLevel === 'LOW').length,
        VERY_LOW: risks.filter(r => r.riskLevel === 'VERY_LOW').length
    };

    doc.setFont('helvetica', 'bold');
    doc.text('Risk Distribution:', 20, yPos);
    yPos += 10;

    doc.setFont('helvetica', 'normal');
    Object.entries(riskCounts).forEach(([level, count]) => {
        const percentage = risks.length > 0 ? ((count / risks.length) * 100).toFixed(1) : '0.0';
        doc.text(`• ${level}: ${count} risks (${percentage}%)`, 25, yPos);
        yPos += 8;
    });

    yPos += 10;

    // Key findings
    doc.setFont('helvetica', 'bold');
    doc.text('Key Findings:', 20, yPos);
    yPos += 10;

    doc.setFont('helvetica', 'normal');
    if (riskCounts.CRITICAL > 0) {
        doc.text(`• ${riskCounts.CRITICAL} critical risks require immediate attention`, 25, yPos);
        yPos += 8;
    }
    if (riskCounts.HIGH > 0) {
        doc.text(`• ${riskCounts.HIGH} high-priority risks need action within 90 days`, 25, yPos);
        yPos += 8;
    }

    const avgRiskScore = risks.length > 0
        ? (risks.reduce((sum, r) => sum + r.riskScore, 0) / risks.length).toFixed(2)
        : '0.00';
    doc.text(`• Average risk score: ${avgRiskScore}/25`, 25, yPos);
    yPos += 8;

    // Top 3 risks
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Top Priority Risks:', 20, yPos);
    yPos += 10;

    const topRisks = risks
        .sort((a, b) => b.riskScore - a.riskScore)
        .slice(0, 3);

    doc.setFont('helvetica', 'normal');
    topRisks.forEach((risk, index) => {
        doc.text(`${index + 1}. ${risk.gap.substring(0, 60)}${risk.gap.length > 60 ? '...' : ''}`, 25, yPos);
        yPos += 6;
        doc.text(`   Risk Score: ${risk.riskScore}/25 (${risk.riskLevel})`, 25, yPos);
        yPos += 10;
    });

    doc.addPage();
};

const generateRiskMatrix = (doc: jsPDF, risks: PDFRiskData[]) => {
    let yPos = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Risk Matrix Analysis', 20, yPos);
    yPos += 20;

    // Create risk matrix data
    const matrixData: number[][] = Array(5).fill(null).map(() => Array(5).fill(0));

    risks.forEach(risk => {
        const likelihoodIndex = risk.likelihood - 1;
        const impactIndex = risk.impact - 1;
        if (likelihoodIndex >= 0 && likelihoodIndex < 5 && impactIndex >= 0 && impactIndex < 5) {
            matrixData[4 - likelihoodIndex][impactIndex]++;
        }
    });

    // Matrix table
    const matrixHeaders = ['Likelihood\\Impact', '1 (Minimal)', '2 (Low)', '3 (Moderate)', '4 (High)', '5 (Critical)'];
    const matrixRows = [];

    const likelihoodLabels = ['5 (Almost Certain)', '4 (High)', '3 (Moderate)', '2 (Low)', '1 (Remote)'];

    matrixData.forEach((row, index) => {
        const rowData = [likelihoodLabels[index], ...row.map(count => count.toString())];
        matrixRows.push(rowData);
    });

    autoTable(doc, {
        head: [matrixHeaders],
        body: matrixRows,
        startY: yPos,
        theme: 'grid',
        styles: {
            fontSize: 10,
            cellPadding: 3,
            halign: 'center'
        },
        headStyles: {
            fillColor: [31, 41, 55],
            textColor: [255, 255, 255],
            fontStyle: 'bold'
        },
        didParseCell: function (data: any) {
            // Color code cells based on risk level
            if (data.section === 'body' && data.column.index > 0) {
                const likelihood = 5 - data.row.index;
                const impact = data.column.index;
                const riskScore = likelihood * impact;

                if (riskScore >= 21) {
                    data.cell.styles.fillColor = [153, 27, 27]; // Critical
                    data.cell.styles.textColor = [255, 255, 255];
                } else if (riskScore >= 16) {
                    data.cell.styles.fillColor = [220, 38, 38]; // High
                    data.cell.styles.textColor = [255, 255, 255];
                } else if (riskScore >= 9) {
                    data.cell.styles.fillColor = [245, 158, 11]; // Medium
                    data.cell.styles.textColor = [0, 0, 0];
                } else if (riskScore >= 4) {
                    data.cell.styles.fillColor = [251, 191, 36]; // Low
                    data.cell.styles.textColor = [0, 0, 0];
                } else {
                    data.cell.styles.fillColor = [16, 185, 129]; // Very Low
                    data.cell.styles.textColor = [255, 255, 255];
                }
            }
        }
    });

    // Legend
    yPos = (doc as any).lastAutoTable.finalY + 20;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Risk Level Legend:', 20, yPos);
    yPos += 10;

    const legend = [
        ['Critical (21-25)', [153, 27, 27]],
        ['High (16-20)', [220, 38, 38]],
        ['Medium (9-15)', [245, 158, 11]],
        ['Low (4-8)', [251, 191, 36]],
        ['Very Low (1-3)', [16, 185, 129]]
    ];

    doc.setFont('helvetica', 'normal');
    legend.forEach(([label, color]) => {
        doc.setFillColor(color[0] as number, color[1] as number, color[2] as number);
        doc.rect(25, yPos - 4, 8, 6, 'F');
        doc.text(label as string, 38, yPos);
        yPos += 8;
    });

    doc.addPage();
};

const generateDetailedFindings = (doc: jsPDF, risks: PDFRiskData[]) => {
    let yPos = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Detailed Risk Findings', 20, yPos);
    yPos += 20;

    // Sort risks by score (highest first)
    const sortedRisks = risks.sort((a, b) => b.riskScore - a.riskScore);

    // Create table data
    const tableData = sortedRisks.map(risk => [
        risk.questionId.toString(),
        risk.level.toUpperCase(),
        risk.gap.substring(0, 40) + (risk.gap.length > 40 ? '...' : ''),
        `${risk.likelihood}/${risk.impact}`,
        risk.riskScore.toString(),
        risk.riskLevel,
        risk.mitigation.substring(0, 35) + (risk.mitigation.length > 35 ? '...' : '')
    ]);

    autoTable(doc, {
        head: [['ID', 'Level', 'Security Gap', 'L/I', 'Score', 'Risk Level', 'Mitigation']],
        body: tableData,
        startY: yPos,
        theme: 'striped',
        styles: {
            fontSize: 8,
            cellPadding: 2
        },
        headStyles: {
            fillColor: [31, 41, 55],
            textColor: [255, 255, 255],
            fontStyle: 'bold'
        },
        columnStyles: {
            0: { cellWidth: 15 },
            1: { cellWidth: 20 },
            2: { cellWidth: 50 },
            3: { cellWidth: 15 },
            4: { cellWidth: 15 },
            5: { cellWidth: 25 },
            6: { cellWidth: 45 }
        },
        didParseCell: function (data: any) {
            // Color code risk level column
            if (data.section === 'body' && data.column.index === 5) {
                const riskLevel = data.cell.text[0];
                switch (riskLevel) {
                    case 'CRITICAL':
                        data.cell.styles.fillColor = [153, 27, 27];
                        data.cell.styles.textColor = [255, 255, 255];
                        break;
                    case 'HIGH':
                        data.cell.styles.fillColor = [220, 38, 38];
                        data.cell.styles.textColor = [255, 255, 255];
                        break;
                    case 'MEDIUM':
                        data.cell.styles.fillColor = [245, 158, 11];
                        data.cell.styles.textColor = [0, 0, 0];
                        break;
                    case 'LOW':
                        data.cell.styles.fillColor = [251, 191, 36];
                        data.cell.styles.textColor = [0, 0, 0];
                        break;
                    case 'VERY_LOW':
                        data.cell.styles.fillColor = [16, 185, 129];
                        data.cell.styles.textColor = [255, 255, 255];
                        break;
                }
            }
        }
    });

    doc.addPage();
};

const generateRecommendations = (doc: jsPDF, risks: PDFRiskData[]) => {
    let yPos = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Risk Treatment Recommendations', 20, yPos);
    yPos += 20;

    // Immediate actions (Critical risks)
    const criticalRisks = risks.filter(r => r.riskLevel === 'CRITICAL');
    if (criticalRisks.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Immediate Actions Required (Critical Risks)', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        criticalRisks.slice(0, 5).forEach((risk, index) => {
            doc.text(`${index + 1}. ${risk.gap}`, 25, yPos);
            yPos += 6;
            doc.text(`   Mitigation: ${risk.mitigation}`, 25, yPos);
            yPos += 6;
            doc.text(`   Timeline: Immediate (within 30 days)`, 25, yPos);
            yPos += 10;
        });
    }

    // High priority actions
    const highRisks = risks.filter(r => r.riskLevel === 'HIGH');
    if (highRisks.length > 0) {
        yPos += 5;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('High Priority Actions (30-90 days)', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        highRisks.slice(0, 5).forEach((risk, index) => {
            doc.text(`${index + 1}. ${risk.gap}`, 25, yPos);
            yPos += 6;
            doc.text(`   Mitigation: ${risk.mitigation}`, 25, yPos);
            yPos += 6;
            doc.text(`   Timeline: 30-90 days`, 25, yPos);
            yPos += 10;
        });
    }

    // General recommendations
    yPos += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('General Recommendations', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const recommendations = [
        'Establish a formal risk management program with regular assessments',
        'Implement a risk register to track remediation progress',
        'Conduct quarterly risk reviews and updates',
        'Provide security awareness training for all staff',
        'Establish incident response and business continuity plans',
        'Regular penetration testing and vulnerability assessments'
    ];

    recommendations.forEach((rec, index) => {
        doc.text(`${index + 1}. ${rec}`, 25, yPos);
        yPos += 8;
    });

    // Footer
    yPos += 20;
    doc.setFontSize(8);
    doc.text(`Report generated on ${new Date().toLocaleDateString()} by INSA Risk Analysis System`, 20, yPos);
};